### ISSUE TITLE
Assign menu class to the list

### ISSUE THREAD

**Issue by ShylovDmitry** [ShylovDmitry/fe-gold-fond#6]
You should not use div here. Remove this additional tag.
`            <div id="menu">
                <ul class="list-inline">
                    <li><a href="#section1">Экспресс-займы</a></li>
                    <li><a href="#section2">Получить займ</a></li>
                    <li><a href="repay_a_loan.html">Погашение займа</a></li>
                    <li><a href="#section3">О компании</a></li>
                    <li><a href="#section4">Блог</a></li>
                    <li class="active"><a href="loan_app.html">Заявка на заем</a></li>
                </ul>
            </div>`

**Comment by slavikohura** [comment]
Fixed #6
